#!/bin/bash

printf "Collecting data. Depending on repository size, this might take a moment."

# color shortcuts
red='\x1b[1;31m'
green='\x1b[1;32m'
blue='\x1b[1;34m'
white='\x1b[1;37m'
NC='\x1b[0m'

# get and format the most recent date
date=`git log -1 | grep "^Date:" | gawk '{printf "%s %s, %s - %s", $3, $4, $6, $5}'`

# user information
usermail=`git config --get user.email`
username=`git config --get user.name`

# getting number of commits
nCommits=`git shortlog -s -e | grep -e "$usermail" | sed -r -e 's/^[\ \t]*([0-9]+).*$/\1/'`

# getting number of total commits
tCommits=`git shortlog | grep -E '^[ ]+\w+' | wc -l`

# getting number of different files
nFiles=`git log --author "$usermail" --pretty=tformat: --numstat | sed -e "/^$/d" | gawk ' BEGIN{} {printf $3"\n"} END{}' | sort -u | wc -l`

# getting total number of files
tFiles=`git log --pretty=tformat: --numstat | sed -e "/^$/d" | gawk ' BEGIN{} {printf $3"\n"} END{}' | sort -u | wc -l`

# info text
printf "\n\n"
printf ">> Repository report <<\n"
echo
printf "$white  Last commit date#$blue%s
$white  Current user#$blue%s\n
$white  Commits by user#$blue%s of %s\n
$white  Files changed#$blue%s of %s\n" "$date" "$username" "$nCommits" "$tCommits" "$nFiles" "$tFiles" | column -t -s "#"
echo
printf "$white  Total diff stats\n"

# get filtered git log, sort out lines, sum up and display it
git log --author "$usermail" --pretty=tformat: --numstat |
sed -e "/^-/d" |
sed -e "/^$/d" |
gawk '
BEGIN {
	a = 0
	s = 0
	d = 0
}
{
	a += $1
	s += $2
	d += $1 - $2
}
END {
	if(a >= s) {
		w = a
	} else {
		w = s
	}
	
	t = w
	w = 3
	
	while(t >= 10) {
		t = int(t/10)
		w++
	}
	w += 2

	printf "'$green'%"w"s  ++\n'$red'%"w"s  --\n'$white'%"w"s  total diff\n", a, s, d
}
'